title: Mueez Ahmed
email: mueezahmad69@gmail.com
description: >-
  Full-Stack Engineer • Cloud Architect • AI Systems Designer.
  Portfolio showcasing projects in MERN, Next.js, AWS, and AI/ML.
url: "https://mueezahmed455.github.io"
github_username: mueezahmed455

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

collections:
  projects:
    output: true
    permalink: /projects/:path/
  posts:
    output: true
    permalink: /blog/:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "default"

sass:
  style: compressed
  sass_dir: assets/css

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
